# Generated by Django 3.2.12 on 2022-02-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.IntegerField(default=5),
        ),
    ]
